### ISSUE TITLE
Error parsoidserver

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcpedia#106]
Using Chrome, I get the following error when I click on Edit : "Error loading data from server: 500: parsoidserver-http: HTTP 500. Would you like to retry" http://www.gcpedia.gc.ca/gcwiki/index.php?title=GCdirectory,_GEDS_and_GEDS_2.0/SMTP_address_exchange_(SMTPAX)&veaction=edit

![image](https://user-images.githubusercontent.com/23527358/40379561-6474ff7a-5dc4-11e8-9b6a-99ec373b1897.png)

**Comment by KevinChagnon** [comment]
Freshdesk: 
https://support.gctools-outilsgc.ca/helpdesk/tickets/3609

**Comment by KevinChagnon** [comment]
Ilia Salem added a note (Freshdesk): Look like something on the page is causing an error with the service that handles a lot of the work behind the visual editor so I guess that makes whatever it is not supported by the version we have on gcpedia… I would suggest testing it out on the external wiki if it’s not an issue (protected content-wise) to see if that version also causes errors. In any case it looks like that page should be edited the old fashioned way.

**Comment by KevinChagnon** [comment]
I cannot replicate this with another page on GCpedia or on Wiki

Found out that user can View History and then click on Edit Source and it will work without error.
Provided this as a (temp) workaround to the user.

**Comment by Phanoix** [comment]
* Looks like that page is using multilang so the visual editor won't really help anyways.
* It looks like their navbar template is what's breaking it
