### ISSUE TITLE
Displaying recent content on GCcollab wiki

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#108]
As a  user of GCcollab wiki, I need to know what content is available on the GCcollab wiki, without having to perform random searches so that I can explore the wiki site content and find content that is relevant to me, my interest and my work. 

The content should be displayed on the [main page of the Wiki](https://wiki.gccollab.ca/Main_Page), and should be generated automatically, without requiring manual input to update the list - similar to how "[Recently active communities](http://www.gcpedia.gc.ca/wiki/Main_Page)" work on GCpedia.

**Comment by Phanoix** [comment]
Easiest thing to add would be a section with the recent changes included as a template:
```
<div style="make it look good">
{{Special:RecentChanges|
limit=10}}
</div>
```

**Comment by Phanoix** [comment]
Is that what you were looking for?

**Comment by Troy-Lawson** [comment]
@s-duffey see below? is this cool? can we close?

**Comment by s-duffey** [comment]
@Troy-Lawson @Phanoix I am good with that as well as some manual upkeep for featuring communities. Final decision would be with @LemieuxGen though, not sure what exactly was required.

**Comment by LemieuxGen** [comment]
@s-duffey have you checked to see what it will look like on the main page? can this be bilingual? I would like to see it implemented before we close the issue.

**Comment by Phanoix** [comment]
It's multi-lingual by default since it pulls the contents from a special page, anything we add around it like a header, etc. would just need to be handled the same way as the rest of the main page.

**Comment by s-duffey** [comment]
@LemieuxGen how much manual upkeep would we want to have on the Collab home page. Majority of content on GCpedia page is manually updated by members of our team. Here's a visual of what @Phanoix can do automatically ![image.png](https://zube.io/files/tbs-sct/242462a84ef4d63bf4e5c28c3b72d265-image.png)

**Comment by LemieuxGen** [comment]
@s-duffey  I would say let's try to do as little manual upkeep as possible. However, we may want to add a list of active communities? 
For the recent changes, I would like to see how we could possibly make it more visually appealing. @Phanoix any suggestions on how we could go about it?
