### ISSUE TITLE
Remove nofollow from GCpedia user list pages

### ISSUE THREAD

**Issue by 4rsood** [gctools-outilsgc/gcpedia#110]
Please remove nofollow attribute from the robots meta tag : <meta name="robots" content="noindex,nofollow"/>

from the pages:
http://www.gcpedia.gc.ca/wiki/Special:ListUsers
http://www.gcpedia.gc.ca/gcwiki/index.php?title=Special:ListUsers&offset=...

It is preventing Solr crawler to fully index the user list pages

**Comment by 4rsood** [comment]
@Troy-Lawson @Phanoix This issue is still outstanding

**Comment by Phanoix** [comment]
There are a few config variables for these values but I don't think any get quite this specific, will need to do a bit more research.

**Comment by Phanoix** [comment]
c8a4a4d should fix this.
