### ISSUE TITLE
Collab Wiki - Images Don't Resize to fit screen

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcpedia#116]
On Collab wiki, the lack of JS and HTML (including inline styles) means that users can't control images. It would be good to add some styles to the style sheet (or add a completely new style sheet) to the system with at least a few basic controls. One I need in particular is:

 I need something along the lines of #img-resize img{width:100%; height:inherit;} . This will help accessibility, since it will resize long images so they fit on the screen. Otherwise, long images will expand the main content container beyond the edge of the screen, and the user has to scroll horizontally to see text.

This is essentially a roundabout way of getting some control over content formatting, since WET4 is not available.

**Comment by Troy-Lawson** [comment]
images can be resized with wiki markup. or is this referring to something else

**Comment by Troy-Lawson** [comment]
you can also do inline css on the wiki

**Comment by Phanoix** [comment]
It's mostly js that's not available, you can still use inline css as usual and the css extension is also installed which can be used: https://www.mediawiki.org/wiki/Extension:CSS
