### ISSUE TITLE
Certain users cannot request a password reset.

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcpedia#118]
As a user, password resets are showing the following error:

![image](https://user-images.githubusercontent.com/42844328/46673202-41e05d00-cba7-11e8-92eb-ec9b0a8ad08c.png)

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5255
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5392

**Comment by klecuyer** [comment]
@martydonofrio let's bring this up at sprint planning at 11 today

**Comment by Phanoix** [comment]
Re-entered and double-checked the smtp credentials, tested it and it looks like it works now.
