### ISSUE TITLE
An english link on a french page -- GCwiki.

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcpedia#150]
##  An english link on a french page on GCwiki.

un lien de navigation qui paraît en anglais sur les pages françaises.
Je joins une image pour illustrer ce problème. /

## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/45214337/90908696-ac1cd800-e3a2-11ea-9a0d-124adc80e3dc.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
The extension is no longer maintained, we should consider removing it https://www.mediawiki.org/wiki/Extension:Favorites

**Comment by Phanoix** [comment]
In the meantime I at updated the instances of this I could find through Mediawiki:<language-variable> pages starting with the one in the screenshot.
