### ISSUE TITLE
French corrections -- GCwiki

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcpedia#151]
## I noticed a typo on the French GCwiki homepage. Instead of saying 'chercher le wikicode' it says 'Changer le wikicode'

also

On the homepage, under the language toggle it says 'francais cadien' instead of 'francais canadien'

also

User noticed that when they are saving changes to a page on GCwiki that the French page still has some English words. 

## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/45214337/88964752-d1249c00-d277-11ea-9e9e-e631fda8e22b.png)

![image](https://user-images.githubusercontent.com/45214337/88964914-08934880-d278-11ea-8be8-a98eda0b2820.png)

- When Francais Ca(na)dien is selected

![image](https://user-images.githubusercontent.com/45214337/88964766-d71a7d00-d277-11ea-99ae-4795401ccf9b.png)

![image](https://user-images.githubusercontent.com/45214337/88965615-0382c900-d279-11ea-93a7-57fe7e744a82.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
For the first one, it's referring to this and isn't a typo https://fr.wikipedia.org/wiki/Fran%C3%A7ais_louisianais

**Comment by Phanoix** [comment]
The second one seems to be a cache issue, currently clearing cache when switching language seems to help.
It also doesn't seem to be as much of an issue for the more recent versions of mediawiki / visual editor, which I should be getting around to upgrading to in the not too distant future
