### ISSUE TITLE
GCpedia Mediawiki Extension Review

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcpedia#156]
- What is currently supported
- What is supported with PostgreSQL 
- What should we continue to support? (ex free form HTML)
- Create a script to review extension usage

**Comment by vid** [comment]
Here's a list of extensions used by gcpedia with their latest versions, and some Postgres related notes. https://docs.google.com/spreadsheets/d/1BRX2aFTPkR64kCbC2V4tWPSuiJjboIz57ZQpadaXp3k/edit?usp=sharing

**Comment by Phanoix** [comment]
Using the same list of extensions in the same order I'm compiling some usage metrics here: https://docs.google.com/spreadsheets/d/19YLVCdykqErxmVVaF2TSbggn3qGmVMJc-4jyabumsag/edit?usp=sharing

**Comment by vid** [comment]
The wikis are a historical record of internal and extranet GC communications, including metadata such as page edits. Some pages are transcluded from other pages using specific extensions.

They will be continue to be used as required by users, with versions and extensions aligned and a single sign-on option, as well as opportunities to finely integrate with other system components (eg content between sites using the API). 

## Aspects to evaluate;

1. * when should we decide to deprecate functionality or rendered content?
    1. number of users? 
    1. last use?
    1. support difficulty
1. level of effort to preserve rendered results
    1. alternate renderers (SMW)
    1. flatten content
1. other value-adds
    1. auto categorize
    1. featured content (SMW)
    1. upgrade considerations
        1. updated skins

## Analysis methods:

1. inventory of extensions ([latest version](https://docs.google.com/spreadsheets/d/19YLVCdykqErxmVVaF2TSbggn3qGmVMJc-4jyabumsag/edit#gid=0))
3. Mediawiki statistics page
4. Google Analytics dashboard (pre-G4)
5. GA4 API
6. Web logs (if GA is not fine enough detail)

## Analysis output

1. statistical and qualitative summaries;
    1. active* users (mw)
    1. recent* page edits
    1. recent* page reads
    1. extension usage
1. impact of deprecating or replacing complex extensions

## Next steps

1. meet with UX
1. organize resources & access
1. learn enough GA
1. generate output for reviews

**Comment by vid** [comment]
I suggest we mark this ticket as closed and decompose further work in #165.
