### ISSUE TITLE
GCconnex to GCpedia

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcpedia#16]
GCPED-33
From: Denise.Eisner@tbs-sct.gc.ca 
 
 Msg: When clicking GCConnex on the global nav bar on GCPedia, you are presented with the splash screen for GCConnex. If I’m on an English page on GCPedia, I would expect to see the English landing page on GCConnex.

**Comment by Phanoix** [comment]
This would require some changes to how GCconnex handles language selection.
