### ISSUE TITLE
Issue uploading file in GCpedia

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcpedia#164]
A user is having issues uploading a file on GCpedia. Information on the issue:

I have been trying to upload some changes to this GCPedia page for a couple weeks: “[Editing PAC - GCpedia](https://www.gcpedia.gc.ca/gcwiki/index.php?title=PAC&action=edit)”

Every time I try to upload my changes, I get redirected to a blank page which displays: “The requested URL was rejected. Please consult with your administrator. Your support ID is: 2347206242400376245”

**Comment by Phanoix** [comment]
that sounds like an error with the ingress / firewall side, I'll pass it on
