### ISSUE TITLE
Merge in Gcpedia-only extensions

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcpedia#172]
Some of these have been in the default branch for a while, add in the rest. Drop, update, or swap to submodules of upstream as appropriate

aside from the gcpedia/wiki skin tweaks and the saml / openid auth extensions, the set of gcpedia extensions is a superset of the gcwiki ones

there are 4 custom extensions that will need to be updated or partially rewritten to work properly with the latest version of mediawiki and just overall be easier to maintain further:
 - ~[ ] GC_tcDisclaimer~
 - ~[ ] ROTedits~  - was only used for a specific cleanup exercise years ago and not really relevant now, will probably need a re-write if we ever need something like it again
 - [x] awards
 - [x] EmailUpdate
 - [x] customUserCreateForm - this was technically based on an extension we didn't write at first, but by now the vast majority gcpedia specific and the one that inspired it has long since been abandoned, so might as well finish that us and  rewrite it as gcpediaUserCreateForm

 - ~mwSimpleSamlAuth~ is no longer supported, might be a good time to consider dropping support in and eventually use openid auth like gcwiki
 - video extensions: 
   - most of the are for flash video which makes dropping them an easy decision, can be replaced by https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:TimedMediaHandler for embedding uploaded media files
   -  FramedVideo is for embedding external videos but has been abandoned for several years now, gcwiki uses the IframePage extension for youtube video embedding, which can similarly used in gcpedia and can likely handle embedding videos from other services as well
 - [x] #187 - this is no longer maintained, this is a good chance to figure out if we want to keep it or not. It currently pre-populates a user's user page with an empty profile-like template. If we keep this functionality it can be re-written as a fork of the NewUserMessage extension which does almost the same thing.

**Comment by Phanoix** [comment]
-  to submodule => can be pulled in from upstream unmodified as a submodule
- bundled => is now bundled with the core mediawiki and can get it from there
- =  => already used in external wiki / gcwiki and was updated as a result of step 1
- ?* => the parts that will not be as straight-forward, some might need to be dropped


AJAXPoll  -  to submodule
	
AjaxShowEditors  -  to submodule
	
CSS =
	
CategoryTree   - bundled
	
CategoryWatch =
	
CharInsert =
	
Cite   - bundled
	
Collection ?
	
ContactPage - still needed?
	
DeletePagesForGood =
	
EditUser =
	
EmailUpdate =
	
ExtVideo ?
	
Favorites   borked in 1.40 -> ? same issue in external wiki
	
FramedVideo ?
	
GCRandomImage test, still used?
	
GC_Messages =
	
GC_tcDisclaimer test
	
Gadgets   - bundled
	
ImageMap   - bundled
	
InputBox   - bundled
	
Lingo =
	
LookupUser =
	
MagicNoNumberedHeadings =
	
MagicNumberedHeadings =
	
MobileFrontend =
	
MsCalendar  -  to submodule
	
Multilang =
	
NewUserMessage  -  to submodule
	
NewUserPage ? - maintain or drop
	
ParserFunctions   - bundled
	
Poll ? - unmaintained, drop in favour of AJAXPoll? seems to have the same syntax
	
ROTedits ? still needed?
	
RSS =
	
Renameuser-- merged into core
	
ReplaceText   - bundled
	
Sudo =
	
TreeAndMenu =
	
UniversalLanguageSelector =
	
UserMerge =
	
Validator ? - still maiintained, but do we use this?
	
VisualEditor   - bundled
	
WikiEditor   - bundled
	
awards ? test
	
customUserCreateForm ? - unmaintained for a long time
	
intersection =
	
mwSimpleSamlAuth ? unmaintained, used for gcconnex - based simple login
	
wikiFlvPlayer ??? do we just drop this one? maybe it'll still work?

**Comment by piet0024** [comment]
Remaining work is in other issues. #192
