### ISSUE TITLE
user asking if he can bulk upload documents on GCpedia

### ISSUE THREAD

**Issue by RimaSakr** [gctools-outilsgc/gcpedia#19]
more precisely: he woudl like the html2wiki extension installed https://www.mediawiki.org/wiki/Extension:Html2Wiki
the question was forwarded to Ilia and here is the response we got : “The closest we have right now is the visual editor’s parser, which does wikitext->html and html->wikitext conversion, however the suggested extension seems to be an import tool for full html web pages with images, etc.
Export/import between mediawiki wikis is quite simple, but I guess what they have can’t export in wikitext, and HTML is the only other usable export format they have available for their pages.
I’ll have to look into it more but it looks like it’ll take a bit of work to get that html import extension set up, and we’ll have to test how well it handles bulk imports.”

Thanks,

**Comment by Troy-Lawson** [comment]
no closing as wiki can still be enhanced

**Comment by Phanoix** [comment]
This one's less of a can we and more of a does it fit with what GCpedia is and will be as part of the new stuff as well.
