### ISSUE TITLE
TimedMediaHandler extension for media uploaded to gcpedia

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcpedia#193]
https://www.mediawiki.org/wiki/Extension:TimedMediaHandler

This is to replace the flash video player extensions that were for embedding videos that were uploaded to gcpedia, though without support for flash media of course.

**Comment by Steph4104** [comment]
@Phanoix Can you provide more context on this task? Is this for the ability to upload video? Not embed
