### ISSUE TITLE
Subject text displays incorrectly (perhaps with pages with accents)

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcpedia#22]
Hi @Phanoix  got a message with the subject like this from gcpedia:

-----Original Message-----
From: GCpedia [mailto:tbs.DoNotReply-NePasRepondre.sct@canada.ca]
Sent: December 1, 2016 12:47 PM
To: Andrecheck, Philippe
Subject: =?UTF-8?Q?GCpedia=20page=20Objectif=202020/ChampionsF/mise=20=C3=A0=20jour=20d=C3=A9cembre=202016/Agence=20de=20d=C3=A9veloppement=20=C3=A9conomique=20du=20Canada=20pour=20les=20r=C3=A9gions=20du=20Qu=C3=A9bec=20has=20been=20changed=20by=20Frederique.R...

Dear Philippe.andrecheck,

The GCpedia page Objectif 2020/ChampionsF/mise à jour décembre
2016/Agence de développement économique du Canada pour les régions du
Québec has been changed on 1 December 2016 by Frederique.Roy-lavoie1, see
http://www.gcpedia.gc.ca/wiki/Objectif_2020/ChampionsF/mise_%C3%A0_jour_d%C3%A9cembre_2016/Agence_de_d%C3%A9veloppement_%C3%A9conomique_du_Canada_pour_les_r%C3%A9gions_du_Qu%C3%A9bec
for the current revision.

See
http://www.gcpedia.gc.ca/gcwiki/index.php?title=Objectif_2020/ChampionsF/mise_%C3%A0_jour_d%C3%A9cembre_2016/Agence_de_d%C3%A9veloppement_%C3%A9conomique_du_Canada_pour_les_r%C3%A9gions_du_Qu%C3%A9bec&diff=next&oldid=1713614
to view this change.

See
http://www.gcpedia.gc.ca/gcwiki/index.php?title=Objectif_2020/ChampionsF/mise_%C3%A0_jour_d%C3%A9cembre_2016/Agence_de_d%C3%A9veloppement_%C3%A9conomique_du_Canada_pour_les_r%C3%A9gions_du_Qu%C3%A9bec&diff=0&oldid=1713614
for all changes since your last visit.

Editor's summary: -

Contact the editor:
mail:
http://www.gcpedia.gc.ca/wiki/Special:EmailUser/Frederique.Roy-lavoie1
wiki: http://www.gcpedia.gc.ca/wiki/User:Frederique.Roy-lavoie1

There will be no other notifications in case of further activity unless
you visit this page. You could also reset the notification flags for all
your watched pages on your watchlist.

		 Your friendly GCpedia notification system
PhilAndrecheck reopened this issue about 9 hours ago
@Phanoix
Phanoix 
commented about 9 hours ago
That one is from GCpedia, I'll have to take a look at it in a later sprint. Should be made into a separate issue in https://github.com/tbs-sct/gcpedia/issues.
Phanoix closed this issue about 9 hours ago
Comment on issue
Sign in to comment
or sign up to join this conversation on GitHub
 Desktop version

**Comment by Phanoix** [comment]
We haven't done anything to the GCpedia notification system, so maybe there's some settings that will have it encode the subjects properly.

**Comment by Phanoix** [comment]
https://phabricator.wikimedia.org/T21001

**Comment by cyclingzealot** [comment]
That's quite a detailed answer in that URL!  @Phanoix L do you think there's one encoding gcpedia can ouput all it's email to or do you think implementing the recommended feature is required?


> All what MediaWiki COULD do is to include a preference in your user account to specify an encoding that you can read with YOUR email agent, and that will be used by default if subject lines contain only characters from your preferred selected charset (otherwise it will still fallback to UTF-8, using Base64 or Quoted-Printable also according to your preferences, or using a transliteration into your preffered charset if its possible without excessive losses).

**Comment by ToferC** [comment]
@PhilAndrecheck @Phanoix - is this still ongoing? Moving out of blocked.

**Comment by Phanoix** [comment]
If this is still happening maybe it'll be resolved with a mediawiki upgrade, or more likely with upgrades of the users' email clients.

**Comment by Troy-Lawson** [comment]
closed until we are looking at revamping notification system
