### ISSUE TITLE
Evaluate updated / unmaintained / custom extensions

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gcpedia#237]
These Mediawiki extensions are no longer maintained:

* Multilanguage - unmaintained, no database changes - use repo version
* MagicNoNumberedHeadings - unmaintained, no database changes - use repo version

Determine how they are used in current wikis and respond appropriately.

These extensions are using updated versions:

* MW-OAuth2Client
* TreeAndMenu

* EmailUpdate - custom, use repo version. Tested with 1.40

**Comment by vid** [comment]
multilang (and other <tag> based extensions) could probably be rewritten as a Web Component. That would make it entirely client side and therefore less maintenance overhead and risk.

**Comment by vid** [comment]
The NumberedLists extensions rely on functionality that is [no longer supported](https://issue-tracker.miraheze.org/T8897). 
This results in a page error using the numbered header extensions, found in [this test](https://github.com/gctools-outilsgc/gcpedia/blob/use-composer-git/haibun/e2e/features/extensions/numbered-headings.feature).

A workaround is to [use client-side Javacript](https://www.mediawiki.org/wiki/Snippets/Auto-number_headings).

**Comment by Phanoix** [comment]
for numbered headings, since the option in preferences for numbered headings has been removed with the parser flag removal, there should be no reason for __NoNumberedHeadings__ as that's the only way they'd appear anyways now. For __NumberedHeadings__ the js / css workaround seems to be the way to go
