### ISSUE TITLE
write tests for custom extensions

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gcpedia#238]
Multilanguage, ~MagicNoNumberedHeadings~, ~MagicNumberedHeadings~

**Comment by vid** [comment]
Tests were created, issues were found with the NumberedHeadings extension. #237.

**Comment by Phanoix** [comment]
no numbered headings magic word no longer needed as the only way to have numbered headings in recent versions of mediawiki is with an extension like MagicNumberedHeadings

**Comment by Phanoix** [comment]
Numbered headings one isn't being used so that one can be dropped too
