### ISSUE TITLE
Improve e2e reviews in github actions

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gcpedia#246]
Reviews are created after e2e tests run in a github action. They are published to a specific branch used for github pages. A token is required, which should be a role token. When the token expires, the tests fail.

Additionally, the official Playwright docker container fails when a library is not using its latest version. Use a vanilla container.

Finally, update the github action so the failing test passes.

Successful test run: https://github.com/gctools-outilsgc/gccollab-frontend/actions/runs/8927541475/job/24521149516

Unsuccessful test run: https://github.com/gctools-outilsgc/gcpedia/actions/runs/9063393225/job/24899237989

**Comment by piet0024** [comment]
Review with development and UX team.
