### ISSUE TITLE
The mysql database type must be specified as innodb to be supported by the managed database.

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gcpedia#257]
Specify type in initial creation. and the GC_Disclaimer extension.

**Comment by Phanoix** [comment]
GC_Disclaimer isn't going to be used for now, if we do end up using it again it'll need at least a partial rewrite.

**Comment by Phanoix** [comment]
for now we have to do this by keeping a custom copy of https://github.com/gctools-outilsgc/gcpedia/blob/main/maintenance/tables-generated.sql
