### ISSUE TITLE
Analysis of gc wikis usage - stats

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gcpedia#268]
Determine how accounts and resources are being used on GCPedia and GCWiki.

## Resources

in addition to accounts;

* pages
  *  exclude templates and other transcluded pages
* files
  * outdated files

## Access data

Determine cut-off for each of these data sources;

* access logs
  * ~2 weeks
* Google Analytics
  * Previous version of GA data before June 2023 is no longer available.

Since access data is limited, some measures will have to be on a statistical basis to the limits of the data.

**Comment by vid** [comment]
## Reports in the past X days:

* Number of articles / change
  * MW API
* Active users
  * MW API
* Number / % of pages edited
  * MW API
* Number of pages created
  * MW API
* Number of users created
  * MW API
  *
* Unique visitors
   * GA
* Unique page visits
  * Access logs
  * GA?
* % of pages visited

**Comment by vid** [comment]
Top 15 pages accessed

**Comment by vid** [comment]
Page response time

**Comment by vid** [comment]
Liveness check stats

**Comment by Phanoix** [comment]
Unique page visits from access logs wouldn't really work because of how requests are routed, just page requests in total would, GA should have the data for that though.
