### ISSUE TITLE
Search links to incorrect page when special characters displayed

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcpedia#27]
This is probably more a search issue than a GCpedia issue, however, when a result show a URL in GCpedia that contains special characters, in this case É, it changes the URL (to the % or HTML equivalent value?) so that when the user clicks on the link, they're taken to a page that does not exist:
![search](https://cloud.githubusercontent.com/assets/22220521/21681962/bf2da3f8-d31f-11e6-96a8-69ad6b58a69d.PNG)

**Comment by pandurx** [comment]
emailed Rajeev, waiting for a response.

**Comment by cyclingzealot** [comment]
Update for anyone trying to fix this: My understanding is that access to `intranet.canada.ca` is required.   Thus I can't work on this.

**Comment by pandurx** [comment]
This GCpedia search issue is resolved
