### ISSUE TITLE
New Update the privacy terms and conditions for GCPedia

### ISSUE THREAD

**Issue by Steph4104** [gctools-outilsgc/gcpedia#272]
[PRD_Terms and Conditions - Edits Completed_20241105-EN-FR.pdf](https://056gc.sharepoint.com/:b:/r/sites/OCIO-DDP-_BDPI-SDPN/GC%20Collaboration%20Tools/Product/Terms%20%26%20Conditions/Terms%20%26%20Conditions%20-%20Privacy%20Statement%202024/PRD_Terms%20and%20Conditions%20-%20Edits%20Completed_20241105-EN-FR.pdf?csf=1&web=1&e=AUYiaS)

**Comment by vid** [comment]
T&C have been updated using a link to the uploaded PDF.
