### ISSUE TITLE
Ability to login from any page on GCpedia

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#28]
As a frequent user of GCpedia, I get logged out of GCpedia often and when I want to modify a page or simply login, I get redirected to the login page, then to the main page of GCpedia. I need to have a "quick login" from the login link that appears at the top right corner of the page (same as GCconnex) to that I can login and stay on the same page (or be redirected to the page I was prior to logging in. 

In addition, the "quick login" should automatically sign in users using the Simplified Sign-on, when the user is already connected to GCconnex.

**Comment by Phanoix** [comment]
Proposal: add a simplified login link beside the regular one on that menu.
