### ISSUE TITLE
Unable to proceed with Email address confirmation

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#29]
A user was prompted to confirm his email address before being able to proceed with login in to GCpedia. After clicking on T&Cs (Step 1) and updating his E-mail (Step 2), the Proceed button is still disabled (unable to click on the Proceed button to continue. 
 
![gcepdia - confirm email address - proceed button not working](https://cloud.githubusercontent.com/assets/15378977/21816741/2f336eea-d72f-11e6-98ad-227634ddbf19.png)

After refreshing the page (using the refresh arrow or CTRL+F5), the confirmation screen appeared.

We need to fix the _Proceed_ button to ensure it's easy for users to confirm their email address, without having them guess they need to refresh the page.

**Comment by KevinChagnon** [comment]
Refreshing the page will not always work. Some users reporting that once Proceed is clicked, the page refreshes without the entered data.

**Comment by Phanoix** [comment]
I applied a patch that should solve a lot of the problem users were having with this.

**Comment by LemieuxGen** [comment]
@Phanoix will this be part of the next code push at the end of this sprint?

**Comment by Phanoix** [comment]
Since this is on GCpedia and I've been meaning to get it updated for some time now (and there should be no visible difference) I decided not to wait and put it into production yesterday evening.
If there are further or persistent problems with how it works then they should go in here.

**Comment by LemieuxGen** [comment]
@Phanoix great, thanks!

**Comment by LemieuxGen** [comment]
@KevinChagnon You can respond to users who reported this issue (if needed). Thanks!
