### ISSUE TITLE
gcpedia: J'ai besoin que le créateur de PDF fonctionne avec les gabarit

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcpedia#30]
Amélioration d'une fonctionnalité existante

**Comment by Phanoix** [comment]
The new pdf service works much better, especially with templates (the one used in wiki.gccollab.ca). Upgrading to that one should improve generated pdf accuracy for GCpedia as well.

**Comment by Phanoix** [comment]
Already done for the external wiki, blocked by upgrade and server move for gcpedia.
