### ISSUE TITLE
gcpedia: To be automatically signed in when I click login

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcpedia#31]
Enhancement of existing feature - usability and saving users time.  May be part of single-sign-on work.

**Comment by Phanoix** [comment]
I'm assuming this is for the users using the simplified sign-on?

**Comment by ToferC** [comment]
Yes.

**Comment by ToferC** [comment]
Should also set up a redirect back to the originating page where the user selected login.

**Comment by Phanoix** [comment]
is this the same as #28?

**Comment by ToferC** [comment]
Yes.
