### ISSUE TITLE
gcpedia: I'd like us to investigate the option of generating and rendering RSS feeds from GCpedia. More precisely, to install Extension:RSS and Extension:WikiArticleFeeds.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcpedia#32]
New Feature Request
As a Regular User, I need I'd like us to investigate the option of generating and rendering RSS feeds from GCpedia. More precisely, to install Extension:RSS and Extension:WikiArticleFeeds. because As My GCHR reviews its web/GCtools approach to better communicate with its 55,500+ users, we'd like to be able to communicate short/timely message (service interruption, important notifications) via RSS on GCintranet, GCconnex and GCpedia. While GCintranet and GCconnex supports RSS, GCpedia doesn't.
In an ideal world (you'll see i'm not too hard to please), I'd update the feed once and the message would go up via RSS on all our platforms. Extension:RSS would render the latest message in the feed. Extention:WikiArticleFeeds would allow us to turn our NewsaboutMyGCHR template into the feed. As we are not the publisher for GCintranet, we don't want to wait 48 hours to update our website with a service status message that is probably no longer relevant.

pierre-luc.pilon@tbs-sct.gc.ca - 1/25/2017 16:26:16

**Comment by bruno-infotrad** [comment]
Team GCInternational is claiming this issue :-)

bruno.grossmann@international.gc.ca

**Comment by Phanoix** [comment]
Just an update on this one: we've had Extension:RSS installed for some time now, but not the other one.,
