### ISSUE TITLE
gcpedia: A live stream side bar (almost like the live stream of the wire) for pages with a lot of recent activity or most frequently searched groups of the week.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcpedia#35]
New Feature Request
As a Super User, I need A live stream side bar (almost like the live stream of the wire) for pages with a lot of recent activity or most frequently searched groups of the week. because When onboarding users they usually say that they don't use the told because they don't know what to use them for. There is a lot of information on GCpedia and users don't know what to look for if they don't know what is out there. Having a stream of most popular pages and activity will bring content to the user, thus making the use of GCpedia more appealing

erin.chapman@tbs-sct.gc.ca - 2/17/2017 9:09:42

**Comment by bruno-infotrad** [comment]
Team GCInternational is claiming this issue :-)

**Comment by pabrams** [comment]
Sorry if I'm just ignorant of popular culture, but what is "the live stream of the wire"?  Are you talking about the television crime drama "The Wire"?  I've never seen that, but I could imagine a "live stream" web feed of some sort, depicted on that TV show, to which you might be referring.  When I do an internet search for "the live stream of the wire" (without quotes), I get a vblog or something called "The Daily Wire" on livestream.com, so I'm not sure if maybe that's what you're talking about?  
Can you elaborate?  Are you talking about some kind of real-time notification summary, like on the rightmost side of a facebook browser tab?
