### ISSUE TITLE
Notification email subject line displaying codes instead of accents

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcpedia#45]
Received a notification from GCpedia about a page I am watching.
The page is in French and the URL on GCpedia uses accents.

The subject line of the email notification is: 
=?UTF-8?Q?GCpedia=20page=20Objectif=202020/ChampionsF/mise=20=C3=A0=20jour=20d=C3=A9cembre=202016/Agence=20f=C3=A9d=C3=A9rale=20de=20d=C3=A9veloppement=20=C3=A9conomique=20pour=20le=20Sud=20de=20l=E2=80=99Ontario=20has=20been=20changed=20by=20Christy.B...

But the content is fine in English:
The GCpedia page Objectif 2020/ChampionsF/mise à jour décembre
2016/Agence fédérale de développement économique pour le Sud de
l’Ontario has been changed on 25 April 2017 by Christy.Baker1

...and in French:
The GCpedia page Objectif 2020/ChampionsF/mise à jour décembre
2016/Agence fédérale de développement économique pour le Sud de
l’Ontario has been changed on 25 April 2017 by Christy.Baker1

**Comment by Phanoix** [comment]
duplicate of / provides another example for #22, closing.
