### ISSUE TITLE
Statistics Page Not Working in Firefox

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcpedia#46]
The input fields do not have the pop-up calendar for choosing dates, and the graphs/stats do not populate.

**Comment by Phanoix** [comment]
I have noticed the calendar dropdown/popup issue, but haven't had problems with the stats/graphs... do you get anything just loading the landing page for GCpedia stats (http://stats.gctools-outilsgc.ca/gcpedia/) as opposed to page-specific ones?

**Comment by massierick** [comment]
Sorry, my mistake, I should have been more clear. It does populate on page load, hwoever, whenever I try to change the date range using the date format shown on the page ( dd/mm/yyyy ) is doesn't load the data. 

This is particularly interesting, since when I use a browser in which the pop-up calendar works, the calendar formats the date completely differently than the text above the field ( yyyy-mm-dd instead of dd/mm/yyyy ). 

And I just tested it, and it turns out that if I manually enter the date in FF using yyyy-mm-dd, the data will show up. 

It seems that one quick solution would be to fix the field caption, adding the correct date format.

**Comment by Phanoix** [comment]
Thanks, I'll fix that caption for now.

**Comment by massierick** [comment]
You are awesome. Thanks!
