### ISSUE TITLE
Delete orphan files from GCpedia

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#50]
GCpedia ROT - deleted all orphan files from GCpedia.
GCpedia admins should be able to run the script to perform the ROT exercise themselves. 

We need a script to clean up files that are not being used anywhere (orphan files). 
1. Bot will find files
2. File will be added to the category "marked for deletion", which will add a message on the file page that the file is marked for deletion. The message will stay on the page for 2 weeks. 
3. The admin will go back and delete all the files (with one click!) that still have the category associated to it, and deleted the files permanently.

**Comment by Phanoix** [comment]
I've updated the relevant scripts.
Do we want a certain cutoff point time-wise? For example, only do this for files uploaded at least a year ago.

**Comment by LemieuxGen** [comment]
Thanks @Phanoix for working on this! Were there any issues? were all the orphan files deleted?
