### ISSUE TITLE
Delete pages marked for deletion

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#51]
GCpedia ROT - deleted all pages marked for deletion in the GCpedia Main name space.
There are currently numerous pages marked for deletion in GCpedia (with template:delete and template:reduceROT). 
GCpedia admins should be able to run the script to perform the ROT exercise themselves.

We need a script to clean up pages marked for deletion.
1.Bot will find pages
2.Page will be added to the category "marked for deletion", which will add a message on the page that the file is marked for deletion. The message will stay on the page for 2 weeks.
3.The admin will go back and delete all the pages (with one click!) that still have the category associated to it, and deleted the pages (not permanently, only normal delete).

**Comment by Phanoix** [comment]
The bot is ready, we just need to decide on some details, like when it should run.

**Comment by LemieuxGen** [comment]
Thanks @Phanoix for working on this!
