### ISSUE TITLE
GCpedia to Fandom Wikia

### ISSUE THREAD

**Issue by MishaGaudet** [gctools-outilsgc/gcpedia#55]
_**PS:**_ _Fandom Wikia can't be seen on TBS machines._

[Fandom Wikia](http://fandom.wikia.com/) is a really easy to edit Open Source Feature. It's really well made and looks fantastic. Here's a list of page that use this feature : http://fandom.wikia.com/explore

I've created an account to try it out and edit page myself. Their Visual Editor is wonderful and really user friendly. Everything you create in the Visual Editor can be toggle to Wiki code.

Visual Editor:
![image](https://cloud.githubusercontent.com/assets/26441486/26795825/08c55a32-49f5-11e7-83ed-76e1e9fedb0e.png)

Wiki Code:
![image](https://cloud.githubusercontent.com/assets/26441486/26795848/27571bfc-49f5-11e7-80ad-da857730bd8e.png)

It has a huge list of templates and custom info boxs:
![image](https://cloud.githubusercontent.com/assets/26441486/26795931/82b80970-49f5-11e7-97bb-6284c58e1680.png)

Adding an image to an info box is simple:
![image](https://cloud.githubusercontent.com/assets/26441486/26796029/d915efa8-49f5-11e7-83d0-cd2c32d6cd15.png)

It has the Drag and drop feature:
![image](https://cloud.githubusercontent.com/assets/26441486/26796045/ec7c3a84-49f5-11e7-8303-1519a38a3bab.png)

I think that if we have this for our GCpedia, our new users would understand a lot more, because it's user friendly instead of programmer friendly. We would get less help desk tickets, because it's intuitive and our help page would be shorter and focused on experienced users.

Here the code:
http://dev.wikia.com/wiki/Fandom_Open_Source_Library

**Comment by ToferC** [comment]
Approved for consideration for external wiki site. For work this summer.

**Comment by Phanoix** [comment]
It seems to be a newer / customized version of the VisualEditor editor we're using.

**Comment by Phanoix** [comment]
Actually, after having a look at their codebase, wikia seems to be about 10 major versions behind MediaWiki core, so probably an older but customized version. Still, we can probably borrow some of those customization.

**Comment by ToferC** [comment]
Closing as decision has been made to use Mediawiki proper.
