### ISSUE TITLE
Mockup for communities

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcpedia#58]

**Comment by piet0024** [comment]
Here are the proposed wires
Source Editor
![gcpedia_communities-01](https://user-images.githubusercontent.com/7603237/28591117-81defa3e-7152-11e7-9773-bec2d11eea95.jpg)
Visual Editor
![gcpedia_communities-02](https://user-images.githubusercontent.com/7603237/28591134-91277dcc-7152-11e7-9ebb-9b7bb2f1f667.jpg)

The idea is to simply add an audience input in the flow of users creating / editing pages. Once a users adds or changes the audience it can perhaps be simply added as a category and it can be tracked in the page history to see if anyone modified it. Like connex it will not be a required field.

**Comment by Phanoix** [comment]
I'll have to check how easy it would be to add the field to the Visual Editor, otherwise it looks like a good place for it in the article edit flow.
