### ISSUE TITLE
PDF files to open in a new tab or window or call to open Adobe Reader

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcpedia#62]
As a regular user it would be convenient for PDF files linked within a GCpedia page to open in a new tab, window or call for Adobe Reader to open the file.  This would allow me to continue reading the GCpedia page the file was featured on while being able to immediately refer to the PDF document.
Having to right-click and request for my browser to do this for me each time becomes time consuming and annoying
(request from user)

**Comment by Phanoix** [comment]
I get the feeling that if this is implemented other users will not be very happy with the choice being taken away,

**Comment by massierick** [comment]
Most browsers will allow you to choose a default setting for actions taken on specific filetypes - maybe that could work for you for now? For example, in Firefox I can set PDF's to download by default (instead of opening in browser) when I click them.

**Comment by Phanoix** [comment]
If it's decided that this is something we want to do it can be re-opened later.
