### ISSUE TITLE
GCpedia search results show up different between search for ALL tools or just GCpedia

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcpedia#63]
As a user, I want my content to be searchable on GCpedia and all the GCTools, for whoever might be searching for it.

There seem to be discrepancies between the results shown when I search GCpedia and all of the GCTools.

For this user in particular, when I search _Technical Video on Configuration on VoIP Application_ just in GCpedia, the page opens immediately, Or if I search certain keywords in the title, it suggests the article. Search works great.

But when I type the keyword or even the exact title into 'Search GCTools' to search all the tools, this exact same article doesn't come up in the search results. Other GCpedia articles appear, but not this one.

**Comment by Phanoix** [comment]
This is why I kept the GCpedia search even when we got the other one.
The two are completely separate search systems and the GCpedia-specific one is particularly good if you know the title of the article you're looking for like in this example.

**Comment by ToferC** [comment]
This is intended functionality. We need to continue to improve the GCTools search, but no action will be taken on this issue. Closing.
