### ISSUE TITLE
GCpedia/Wiki Navigation Menu Changes

### ISSUE THREAD

**Issue by beckyjeong** [gctools-outilsgc/gcpedia#72]
@LemieuxGen 

1.	Navigation
        a.	Main page
        b.	Communities
        c.	Browse categories
        d.	Random page
2.	Help
        a.	Help
        b.	FAQ
3.	Actions/Tools
        a.	Create a page _(new feature)_
        b.	Upload a file
        c.	Book creator _(previously: Create a book)_
        d.	Special pages
4.	PDF/Print
        a.	Download as PDF
        b.	Printable version
5.	Page Information
        a.	About page _(previously: Page information)_
        b.     Statistics
        c.	Related changes
        d.	Permanent link
        e.	What links here

Please note that:

1. **Sandbox** will be user-specific and will now be placed in the user menu (as a personal sandbox)
2. **Random page** – please ask Chris L for the stats to see if this feature is being utilized and if not, figure out why it isn’t being used – because we still would like to keep this around
3. **Browse categories** - Kept until we have fully implemented recommendation search engine
4. All of these items will include hover+text of their definitions as well was an introductory paragraph of what they are in its respective pages
5. **Contact us** - Combined with Help and FAQ
6. The first 3 groups (**Navigation, Help, Action/Tools**) are general navigation items while the last 2 groups (**PDF/Print and Page information**) are page-specific items. Due to the circumstances, time-constraints and its limitations, we will keep the last 2 groups in the left navigation menu for now but for the rebuild, we are looking to implement these items into its appropriate areas on the page (e.g., top right menu bar in a hamburger menu/drop-down, etc.)
7. **Communities** will be changed to **Functional Communities** once the functional communities has been updated. 

Hover+text definitions:

Menu items | Descriptions
-- | --
Browse categories | System generated page of all categories   created by users
Communities | Category: Index of communities that are   using GCpedia cross-departmentally
Contact us | GCTools contact information
Create a book | Creating a book of GCpedia articles in   a PDF format
FAQ | Frequently asked questions about   GCpedia
Help | Centre for help related resources
Lexiconapedia | Definition of common terms
Main Page | GCpedia home page
Projects | Category: Index of projects
Random page | Random GCpedia page
Recent changes | List of the most recent edits made to   pages
Sandbox | A page designed for testing and   experimenting with wiki syntax
Special pages | List of pages that have no wikitext,   but are generated by the software on demand
Tag cloud | A visual representation of categories   with text size proportional to category size
Upload file | Uploading files to GCpedia

Page specific features | Descriptions
-- | --
Download as PDF | Generating a GCpedia page in a PDF   format
Page information | A page of information on the current   page
Permanent link | A link to a specific version of a wiki   page
Printable version | Generating a GCpedia page in a   printable format
Related changes | List of all recent changes in each   article linked to the current page
Statistics | A page for obtaining statistics about the current page (i.e. page views)
What links here | List of the pages that link to (or   redirect to) the current page

**Comment by Phanoix** [comment]
Updated Navigation, Help menu items

**Comment by Phanoix** [comment]
Do we have the french versions ready for the label/naming changes?

**Comment by LemieuxGen** [comment]
@Phanoix: @beckyjeong is away for the rest of the week. I'll send it to translation and share it back as soon as I have it. 
Can I see the changes to the nav menu before they go live?

**Comment by Phanoix** [comment]
The first 2 headers don't need any code changes to be updated so that part is already done (controlled by MediaWiki:Sidebar). The rest have a demo up for before I update production.

**Comment by LemieuxGen** [comment]
Great, thanks @Phanoix. I should be able to provide the translation tomorrow.

**Comment by LemieuxGen** [comment]
@beckyjeong I added "statistics" to the list of menu items and description.

**Comment by LemieuxGen** [comment]
@Phanoix Here's the translation for the GCpedia menu. Sorry for the delay. 
[Nouveau menu de navigation de GCpedia.docx](https://github.com/gctools-outilsgc/gcpedia/files/1642852/Nouveau.menu.de.navigation.de.GCpedia.docx)

**Comment by Phanoix** [comment]
Most of the language changes can be done in the system message pages, other than that I made the changes for the book / pdf page generator in the language files (note: that extension is being phased out by mediawiki/wikipedia and they're working on getting something else to replace it).
