### ISSUE TITLE
"Illegal username" message when accessing GCpedia after logging in through SSO

### ISSUE THREAD

**Issue by sboots** [gctools-outilsgc/gcpedia#77]
Hi team! When I go to any GCpedia page I get the following message,
`Illegal username: {"en":"Sean.Boots","fr":"Sean.Boots"}`

This looks like it's related to translation support changes, and I've seen it since several months ago (sorry for the late report!) If I'm a unique case, maybe there's some way to force-sign-out of the shared GCconnex/GCpedia single sign on and then try again.

![gcpedia-sso-error-20180124](https://user-images.githubusercontent.com/263472/35358273-0bc86698-0124-11e8-9fa9-e2d7489a7dee.PNG)

Let me know if there's any troubleshooting things I should try! Thanks a ton. 😄

**Comment by Troy-Lawson** [comment]
@sboots I have no idea why this happened but i have removed the link between your gcconnex and gcpedia accounts. If you choose to link them again, please let me know if this happens again
