### ISSUE TITLE
GCwiki Bug Fixes

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#81]
Following a review and testing of GCwiki features and functionality, some bugs were identify. Attached is a list of the fixes required. 
[GCwiki Test.docx](https://github.com/gctools-outilsgc/gcpedia/files/1752739/GCwiki.Test.docx)

**Comment by LemieuxGen** [comment]
FYI - @markwooff @bryan-robitaille @Phanoix

**Comment by Phanoix** [comment]
From the document:
- [ ] Theme
- [ ] Left Navigation Menu
- [ ] User Navigation Menu (top)
- [ ] Rich Text Editor
- [ ] Login
- [ ] Mobile View
- [ ] Others
