### ISSUE TITLE
WIKI: Remove "Statistics" on the left nav menu 

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#90]
When you click "Statistics" in the sidebar the page, it simply refreshes but does not bring you to another page. 
Until we have more content on wiki, please remove the link from the left nav menu. If this can't be done, let's make sure it points to a page.

**Comment by Troy-Lawson** [comment]
@LemieuxGen is this for external wiki or gcpedia?

**Comment by klecuyer** [comment]
@Troy-Lawson done. And this is for the external wiki.
