### ISSUE TITLE
WIKI: Cannot import pages onto the Wiki

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcpedia#94]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need to be able to export pages on GCpedia and be able to import them onto the external Wiki.

## Details on issue or enhancement
I tried exporting pages from GCpedia and importing the file onto "Import pages" on the Wiki. When I try to do this it says "Import failed: No pages to import". (Example shown below). This could be an error within the Wiki import page or an error in the way the pages are being exported onto the file in GCpedia. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

![image](https://user-images.githubusercontent.com/35535700/38627343-c3dc03a4-3d7c-11e8-9758-0d35f0372a3c.png)

**Comment by LemieuxGen** [comment]
high priority item as we are reaching out to key users to start populating and importing content to the wiki. Goal is to start reaching out to users as soon as possible. thanks!

**Comment by LemieuxGen** [comment]
@sabrinatbs Can you confirm if this is still an issue when importing pages?

**Comment by sabrinatbs** [comment]
It seems to be working except for the UX Research page.

**Comment by sabrinatbs** [comment]
Yes everything is working, I believe the problem was the file being exported on GCpedia
