### ISSUE TITLE
GCcollab wiki footer links - redirect

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcpedia#97]
Add redirect to links that appear in the footer (Privacy policy, About wiki, Disclaimers), More details to be provided...

**Comment by JOutram77** [comment]
Privacy Policy // Politique de confidentialité
EN - https://gccollab.ca/privacy
FR - https://gccollab.ca/confidentialite

Terms and Conditions of Use // Conditions d'utilisation
EN - https://gccollab.ca/terms
FR - https://gccollab.ca/termes

I suggest that the 'About wiki' page be populated by @LemieuxGen and team. Some of the text on the Wiki's home page could be used.

**Comment by LemieuxGen** [comment]
Thanks @JOutram77 for providing the links. I will look at text for the "About wiki" page. 
Note: the link to "disclaimer" should be removed, and we'll add an extra link for the ToC.

**Comment by LemieuxGen** [comment]
@Phanoix would it be possible to add the link to the Terms and Conditions of use to the Collab wiki? 
Terms and Conditions of Use // Conditions d'utilisation
EN - https://gccollab.ca/terms
FR - https://gccollab.ca/termes

and also remove the Disclaimer for now? 
![wiki_footer links](https://user-images.githubusercontent.com/15378977/39319817-3cf035ce-4950-11e8-95b3-7d87e9334f7d.PNG)

**Comment by Phanoix** [comment]
Disclaimer item now reads Terms and Conditions of use and links to the terms page.

**Comment by LemieuxGen** [comment]
@Phanoix the link points to ToCs, but it still says "Disclaimer"...

**Comment by Phanoix** [comment]
It now seems to say Terms and Conditions on all pages, if there is any still cached with the old text it should be gone over the weekend.
