### ISSUE TITLE
WIKI: Link on the main French page leads to an English link 

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcpedia#98]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a French user, when I am on the French Wiki and click a link I need it to lead me to the french version of that page

## Details on issue or enhancement
When clicking on "A propos le wiki GCcollab" on the French page it leads to the English help content page on GCtools instead of the French page.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

![image](https://user-images.githubusercontent.com/35535700/38885444-e9d9431e-4240-11e8-808a-c07e6dc9065f.png)

**Comment by sabrinatbs** [comment]
![image](https://user-images.githubusercontent.com/35535700/38886040-c3d1c16c-4242-11e8-87de-201deb3e1961.png)

**Comment by markwooff** [comment]
The link has been updated on the French page to point to the French FreshDesk page.
