### ISSUE TITLE
Create interwiki links and redirects on GCpedia and GCcollab Wiki

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gcpedia#99]
Create code for interwiki links and redirects on GCpedia and GCcollab Wiki so content can be shared or users can be redirect between platforms by content authors. 

Various users have demonstrated this need and are keen to move their content to GCcollab Wiki but would like a redirect in their existing GCpedia pages.

**Comment by Phanoix** [comment]
Interwiki linking is now enabled between the two wikis, for linking from GCpedia to the collab wiki:
```
[[collab:Main Page]]
#REDIRECT [[collab:Main Page]]
```
collab wiki to GCpedia:
```
[[gcpedia:Main Page]]
#REDIRECT [[gcpedia:Main Page]]
```

**Comment by JOutram77** [comment]
Example wiki code:

Eg. 1 - Redirect from GCpedia to GCcollab Wiki
#REDIRECT [[collab:pagenameonGCcollabWiki]]

Eg. 2 - Redirect from GCcollab Wiki to GCpedia
#REDIRECT [[gcpedia:pagenameonGCpedia]]
